# Kindly borrowed the information from @DrAzureAD's AADInternals :) and reformatted
# Also found an additional reference @ https://blog.darrenjrobinson.com/azure-ad-and-microsoft-office365-deep-links-and-sign-in-urls/
# Well-Known Client Ids 

client_ids:
  graph_api:            1b730954-1685-4b74-9bfd-dac224a7b894 # MS Graph API
  aadrm:                90f610bf-206d-4950-b61d-37fa6fd1b224 # AADRM
  exo:                  a0c73c16-a7e3-4564-9a95-2bdf47383716 # EXO Remote PowerShell
  skype:                d924a533-3729-4708-b3e8-1d2445af35e3 # Skype
  www:                  00000006-0000-0ff1-ce00-000000000000 # Office portal
  o365spo:              00000003-0000-0ff1-ce00-000000000000 # SharePoint Online
  o365exo:              00000002-0000-0ff1-ce00-000000000000 # Exchange Online
  dynamicscrm:          00000007-0000-0000-c000-000000000000 # Dynamics CRM
  o365suiteux:          4345a7b9-9a63-4910-a426-35363201d503 # O365 Suite UX
  aadsync:              cb1056e2-e479-49de-ae31-7812af012ed8 # Azure AD Sync
  aadconnectv2:         6eb59a73-39b2-4c23-a70f-e2e3ce8965b1 # AAD Connect v2
  synccli:              1651564e-7ce4-4d99-88be-0a65050d8dc3 # Sync client
  azureadmin:           c44b4083-3bb0-49c1-b47d-974e53cbdf3c # Azure Admin web ui
  pta:                  cb1056e2-e479-49de-ae31-7812af012ed8 # Pass-through authentication
  partnerdashboard:     4990cffe-04e8-4e8b-808a-1175604b879 # Partner dashboard (missing on letter?)
  webshellsuite:        89bee1f7-5e6e-4d8a-9f3d-ecd601259da7 # Office365 Shell WCSS-Client
  teams:                1fec8e78-bce4-4aaf-ab1b-5451cc387264 # Teams
  office:               d3590ed6-52b3-4102-aeff-aad2292ab01c # Office, ref. https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2
  office_online2:       57fb890c-0dab-4253-a5e0-7188c88b2bb4 # SharePoint Online Client
  office_online:        bc59ab01-8403-45c6-8796-ac3ef710b3e3 # Outlook Online Add-in App
  powerbi_contentpack:  2a0c3efa-ba54-4e55-bdc0-770f9e39e9ee # PowerBI content pack
  aad_account:          0000000c-0000-0000-c000-000000000000 # https://account.activedirectory.windowsazure.com
  sara:                 d3590ed6-52b3-4102-aeff-aad2292ab01c # Microsoft Support and Recovery Assistant (SARA)
  office_mgmt:          389b1b32-b5d5-43b2-bddc-84ce938d6737 # Office Management API Editor https://manage.office.com 
  onedrive:             ab9b8c07-8f02-4f72-87fa-80105867a763 # OneDrive Sync Engine
  adibizaux:            74658136-14ec-4630-ad9b-26e160ff0fc6 # Azure portal UI ADIbizaUX
  msmamservice:         27922004-5251-4030-b22d-91ecd9a37ea4 # MS MAM Service API
  teamswebclient:       5e3ce6c0-2b1f-4285-8d4b-75ee78787346 # Teams web client
  azuregraphclientint:  7492bca1-9461-4d94-8eb8-c17896c61205 # Microsoft Azure Graph Client Library 2.1.9 Internal
  azure_mgmt:           84070985-06ea-473d-82fe-eb82b4011c9d # Windows Azure Service Management API
  az_pwsh:              1950a258-227b-4e31-a9cf-717495945fc2 # AZ PowerShell Module
  apple:                f8d98a96-0999-43f5-8af3-69971c7bb423 # Apple Internet Accounts
  elev_acc:             7f59a773-2eaf-429c-a059-50fc5bb28b44 # https://docs.microsoft.com/en-us/rest/api/authorization/globaladministrator/elevateaccess#code-try-0
  spo_man_sh:           9bc3ab49-b65d-410a-85ad-de819febfddc # SPO Management Shell
  aad_pin:              06c6433f-4fb8-4670-b2cd-408938296b8e # AAD Pin redemption client
  msft_sigins:          19db86c3-b2b9-44cc-b339-36da233a3be2 # https://mysignins.microsoft.com
  o365_mobile:          00b41c95-dab0-4487-9791-b9d2c32c80f2 # Office 365 Management (mobile app)
  msft_mdm:             29d9ed98-a469-4536-ade2-f981bc1d605e # Microsoft Authentication Broker (Azure MDM client)
  aad_broker_plugin:    6f7e0f60-9401-4f5b-98e2-cf15bd5fd5e3 # Microsoft.AAD.BrokerPlugin resource:https://cs.dds.microsoft.com
  aad_cloud_app:        38aa3b87-a06d-4817-b275–7a316988d93b # Microsoft AAD Cloud AP
  az_android:           0c1307d4-29d6-4389-a11c-5cbe7f65d7fa # Azure Android App
  intune:               6c7e8096-f593-4d72-807f-a5f86dcc9c77 # Intune MAM client resource:https://intunemam.microsoftonline.com
  authenticator:        4813382a-8fa7-425e-ab75-3b753aab3abb # Authenticator App resource:ff9ebd75-fe62-434a-a6ce-b3f0a8592eaf
  wcd:                  de0853a1-ab20-47bd-990b-71ad5077ac7b # Windows Configuration Designer (WCD)
  aadj_csp:             b90d5b8f-5503-4153-b545-b31cecfaece2 # AADJ CSP
  exchange_rest_pwsh:   fb78d390-0c51-40cd-8e17-fdbfab77341b # Microsoft Exchange REST API Based Powershell
  add_registered_apps:  18ed3507-a475-4ccb-b669-d66bc9f2a36e # Microsoft_AAD_RegisteredApps

# AccessToken resource strings
api_urls:
  aad_graph_api:         https://graph.windows.net
  ms_graph_api:          https://graph.microsoft.com
  azure_mgmt_api :       https://management.azure.com
  windows_net_mgmt_api : https://management.core.windows.net/
  cloudwebappproxy :     https://proxy.cloudwebappproxy.net/registerapp
  officeapps :           https://officeapps.live.com
  outlook :              https://outlook.office365.com
  webshellsuite :        https://webshell.suite.office.com
  sara :                 https://api.diagnostics.office.com
  office_mgmt :          https://manage.office.com
  msmamservice :         https://msmamservice.api.application
  spacesapi :            https://api.spaces.skype.com
